### ISSUE TITLE
~30% of images missing not served properly with last kiwix-serve (nightly)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#108]
~30% of the images are not served properly with kiwix-serve.

The following example has been done with:
* http://download.kiwix.org/zim/wikipedia/wikipedia_ht_all_novid_2017-11.zim
* kiwix-serve from kiwix-tools_linux64_2017-11-14.tar.gz

kiwix-serve is started like this:
```
kiwix-serve --port=8080 wikipedia/wikipedia_ht_all_novid_2017-11.zim
``` 

The problematic behaviour is not constant. It means, on the same page, it is not always (at each retry) the same images which are not loaded properly. What is interesting is that, even in a Firefox private session, if you reload the page again and again this will be alway the same pictures which will be mission (remember private session has no cache)... But if I restart kiwix-serve, then the missing pictures won't be the same.

Here is a list 3 different (re-)loading of the same page "Pari" (wikipedia_ht_all_novid_2017-11/A/Pari.html) with between each a simple stop/start of the kiwix-serve:

![capture_1](https://user-images.githubusercontent.com/1029718/32852972-0ca69376-ca3a-11e7-88e4-dcb9a7730f0e.png)

![capture_2](https://user-images.githubusercontent.com/1029718/32852983-15a28084-ca3a-11e7-96a7-ef1eb6a17a07.png)

![capture_3](https://user-images.githubusercontent.com/1029718/32852989-19bd37a4-ca3a-11e7-95bd-5c5af7617353.png)

Remarks:
* I do not have checked all the pictures presence in the ZIM file, but only one of them (which fails to load time to time) ```zimdump -n I -f -d m/Grandes_Armes_de_Paris.svg.png wikipedia_ht_all_novid_2017-11.zim > Grandes_Armes_de_Paris.svg.png```
* I strongly suspect a buggy mgmt of concurrent accesses between multiple threads/processes.
* This problem has been first reported by @holta here https://github.com/kiwix/kiwix-tools/issues/102

**Comment by mgautierfr** [comment]
I can confirm the issue, I've got it once (but with only one image missing).

However, I can't reproduce it anymore :/ All images are now correctly displayed.

From what I've seen, kiwix-serve returns a 404 for the missing image, even if the request is for this image only.
It may be related the multi-thread code, but I don't think it is a conflict between different threads running in the same time.

The randomness of the issue is also very strange.

Anyway, I'm continuing investigating, but without a stable reproducer, it may take some times...
