### ISSUE TITLE
Implement --suggestion in kiwix-search

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#132]
Without option make a fulltext search (like currently). With option, use the pattern to search suggestions instead.

**Comment by kelson42** [comment]
@julianharty This is what you need to test suggestions (see #131). Implementation is trivial as the kiwix-lib provide the function straight away.

**Comment by julianharty** [comment]
@kelson42 I need more than this as I don't know or understand how the search is expected to behave fully. Please can you also describe, in writing and perhaps diagrams etc., the expected behaviours. 

Currently, I don't understand (or *know*) how search is supposed to behave from a user's perspective, therefore it's hard to identify bugs vs. 'working as expected' as I have little to use as a reference for what to expect. From your comments in #131 your expectations are different to mine e.g. I still don't know / understand why 'Wa' matches 'Warrington' but 'War' does not. That is you've yet to explain the behaviour, rather you've written that it's working as [you] intended. 

Rather than having personal differences of perspective let's have an oracle (a source-of-truth, a common reference point) which we can use collectively to test and evaluate search. BTW: here I mean an Oracle as in https://en.wikipedia.org/wiki/Oracle_(software_testing) rather than https://en.wikipedia.org/wiki/Oracle Some worked examples that explain the expected behaviours would be a great help. As we've discovered from recent discussions when we show examples then we've understood things, words alone are not sufficient.

Thank you. Once I've a better idea of how search is expected to respond I'll be able to continue testing it :)

**Comment by mgautierfr** [comment]
We do not need to add this option.

It is already possible to do a "suggestion" search with the actual `kiwix-serve`.
You simple have to use the url `http://domain.name/suggest?content=zim_name&term=myquery`
instead of `htpp://domain.name/search?content=zim_name&pattern=myquery`

This is even simpler to test the result as the suggestions returned will be json instead of a full html page for search.

**Comment by kelson42** [comment]
@mgautierfr Sorry, I mean kiwix-search
