### ISSUE TITLE
kiwix-search suggestion mode fails if not ft/title Xapian indexes

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#134]
```
$ ./kiwix-search -s wikipedia_de_all_novid_2017-08.zim Beinasco
$ 
```

It should (at least) return `Beinasco` as result.

Probably a bug in kiwix-lib if not in libzim.

Discovered in #130

**Comment by kelson42** [comment]
@MananJethwani I believe this is the last “easy one” of the project. Would be good to get rid of it so we can the focus on harder stuff.

**Comment by maneeshpm** [comment]
@kelson42 In the current version of `kiwix-search`, if we don't have a FT index, the application will exit as per this logic:
https://github.com/kiwix/kiwix-tools/blob/c76bbabd101e47a82b2f80698ac73e0c9208fd6c/src/searcher/kiwix-search.cpp#L108-L113
In my opinion, If we are in suggestion mode and we do not have access to either ft or title index, we should fall back to the legacy approach with `Reader::searchSuggestion()` which utilizes the `findByTitle(<title prefix>)` method to fetch suggestions rather than relying on any index. And this management should be handled by libkiwix itself. Is this the right behavior?

**Comment by kelson42** [comment]
If we are in suggestion mode, then the ft index should play no role. But yes, without title index (xapian) is hould fallback to the zim title index.

**Comment by maneeshpm** [comment]
In the current form of libkiwix, it will require considerable changes to `Searcher` for covering this case as I have mentioned in kiwix/libkiwix#532. Given that we will be dropping the `kiwix::Searcher` soon, it seems better to use `Reader::searchSuggestionsSmart` (that uses zim index as a fallback) in kiwix-search until we have are ready with a more standardized solution in libkiwix.

**Comment by mgautierfr** [comment]
> If we are in suggestion mode, then the ft index should play no role. But yes, without title index (xapian) is hould fallback to the zim title index. Yes, this is something to handle in libkiwix.

This is something you've disagree on (https://github.com/kiwix/kiwix-tools/pull/136)

But, it is probably to libzim to handle the fallback. Especially if we drop the libkiwix wrapper part. We should move the fallback suggestion algorithm in libzim.

**Comment by maneeshpm** [comment]
I agree with @mgautierfr, implementing this will complicate a lot subroutines in libkiwix.

**Comment by kelson42** [comment]
I'm not against having this in the libzim. I thought it would be easier to make it in the libkiwix and that would be acceptable to me. But I guess the current trend is to keep the libkiwix pretty dumb around the suggestions mgmt.

What is important is that the libzim provides everything properly in a same manner like with Xapian. In particular the cache/moving in the result set. This has to be transparent for the users.

@mgautierfr Regarding #126 and your comment, I'm a bit puzzled. Maybe we can discuss this later today bilateraly.

**Comment by kelson42** [comment]
@MananJethwani What is status here. Do we need a new ticket at libzim level? If "yes", would be great to open one please.

**Comment by maneeshpm** [comment]
@kelson42 we are already tracking this at openzim/libzim#564.

**Comment by kelson42** [comment]
@maneeshpm openzim/libzim#564 will fully fix this issue, or does something additional will be needed at libkiwix/kiwix-tools level?

**Comment by maneeshpm** [comment]
@kelson42 Since it's an API change, we will need some small changes wherever we make suggestion search. Namely, the suggestion functions in `kiwix::Searcher` and the `InternalServer::handle_suggest`. I have a PR in the pipeline that does this. I will push it once we are good with the API change.

**Comment by mgautierfr** [comment]
It would be nice to have it right now. Seeing the change in user code for a API change can help to evaluate if the API change is good or not.

**Comment by maneeshpm** [comment]
@mgautierfr We are tracking this [here](https://github.com/kiwix/libkiwix/pull/567). Due to the way `kiwix::Searcher` is written, the solution I made in the PR is more of a workaround rather than a "good" solution. Looking at the fix, I feel that there is a need to handle suggestions and ft search somewhat differently and the new suggestion API will be a good step in this direction. Combined with dropping wrappers, this could have been a much better PR.

**Comment by kelson42** [comment]
Thx to @maneeshpm works, this is finally fixed
