### ISSUE TITLE
Implement HTTP HEAD request support and HTTP Etag header

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#140]
Both are necessary to improve the cache mgmt. The problem we try to fix concerns mostly the kiwix-serve index page. This page is stable, but only within a kiwix-serve run because:
* The kiwix-serve binary might change and as the consequence the content delivered.
* The library of ZIM files can change

But currently this page is delivered basically with a no-cache HTTP directive. This is annoyous because:
* This page is extremely expensive (in CPU) to generate
* We can not simply put a cache directive to keep it

That is why we should put an etag (on all content) and this etag can be simply the time at which kiwix-serve has been started. We should also implement the support of HEAD requests to allow HTTP client to ask for new etag, without asking the (expensive) HTML.

**Comment by mgautierfr** [comment]
> This page is extremely expensive (in CPU) to generate

The page is already generate only once at the launch of `kiwix-serve` process. `kiwix-serve` only serve a static content when a browser request for the index page.

**Comment by veloman-yunkan** [comment]
> We should also implement the support of HEAD requests to allow HTTP client to ask for new etag, without asking the (expensive) HTML.

I think there is some misunderstanding of how ETags are supposed to work. A client doesn't need to issue a HEAD request in order to check if an earlier (cached) version of the resource has gone stale. Instead, the client should issue a conditional GET request with an `If-None-Match` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match), [RFC](https://tools.ietf.org/html/rfc7232#section-3.2)) header containing the ETag value associated with the cached version of the resource. The server will then respond either with a 304 (Not Modified) response with an empty body or with a 200 response accompanied by the new version of the resource.

Of course, the quoted scenario based on HEAD method and checking of the ETag on the client side is also possible, but is there any evidence that it is utilized in practice?

**Comment by kelson42** [comment]
@veloman-yunkan Thank you for your enlighting comment. I can tell you that:
* I was not familliar with the `If-None-Match` workflow
* I have not element to tell more about what are the browsers and Javascript frameworks strategies.
* I know that we use HEAD requests within our scrapers (but this does not impact kiwix-serve)

Even if I would like to simplify the task - and implementing `If-None-Match` makes it more complex to implement - I suspect we should implement both.

**Comment by mgautierfr** [comment]
I was not knowing the `If-None-Match` workflow neither.

It worth to mention that (at least how it is implemented in #348) :
- A HEAD request implies almost the same work that GET request. In both case we search for the article and compute the content (add taskbar, ...). It is just at the end that we don't send the body for a HEAD request (this is done by libmicrohttpd). I am not sure we can easily avoid that (we always need to know the size of the content, its type, ...)
- On the opposite side, `If-None-Match` do less on the server side. We just ensure that the path is valid (the entry exists), handle redirect if needed. We get the content only if we need it. And it is made in one request only.

I don't know how the server you are scrapping are implemented but they may like that you start to use `If-None-Match`.

**Comment by veloman-yunkan** [comment]
> Even if I would like to simplify the task - and implementing If-None-Match makes it more complex to implement - I suspect we should implement both.

Both are already implemented in  kiwix/kiwix-lib#348 with some approximation. As @mgautierfr noticed, the support for the HEAD method is in a sense a parody of a good implementation. The bulk of that PR is more about handling the conditional request (If-None-Match) part. I brought up this question in order to understand whether the implementation of the HEAD method should be optimized or the current version is acceptable.

**Comment by kelson42** [comment]
I guess the current version is acceptable, @mgautierfr decides at the end.
