### ISSUE TITLE
kiwix-serve still crash with kiwix-serve nightly 2018-03-19

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#168]
Tested with kiwix-tools_linux64-2018-03-19.tar.gz,

core dump available at /var/www/library.kiwix.org/core_2018-03-23

```
arguments :
Parsed :
url   : /apple-touch-icon.png
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_content
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'text/html; charset=utf-8'
 - Accept-Ranges: 'bytes'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
----------------------
======================
Requesting :
full_url  : /wikipedia_ru_all/A/html/К/а/т/а/Катасанов,_Александр_Семёнович.html
method    : GET (0)
version   : HTTP/1.0
headers   :
 - Accept : '*/*'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'ru,by;q=0.7,en;q=0.7,kz;q=0.7,ua;q=0.7,*;q=0.1'
 - Connection : 'close'
 - Host : 'library.kiwix.org'
 - User-Agent : 'Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)'
 - X-Forwarded-For : '217.69.133.252'
 - X-Real-IP : '217.69.133.252'
arguments :
Parsed :
url   : /wikipedia_ru_all/A/html/К/а/т/а/Катасанов,_Александр_Семёнович.html
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_content
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'text/html; charset=utf-8'
 - Accept-Ranges: 'bytes'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
----------------------
======================
Requesting :
full_url  : /wikipedia_en_wp1-0.7_2009-05/A/Minneapolis_Saint_Paul.html
method    : GET (0)
version   : HTTP/1.0
headers   :
 - Accept : '*/*'
 - Accept-Charset : 'utf-8;q=0.7,iso-8859-1;q=0.2,*;q=0.1'
 - Connection : 'close'
 - Host : 'library.kiwix.org'
 - User-agent : 'Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)'
 - X-Forwarded-For : '216.244.66.228'
 - X-Real-IP : '216.244.66.228'
arguments :
Parsed :
url   : /wikipedia_en_wp1-0.7_2009-05/A/Minneapolis_Saint_Paul.html
acceptEncodingDeflate : 0
has_range : 0
.............
** running handle_content
Found /A/Minneapolis_Saint_Paul.html
mimeType: application/octet-stream
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'max-age=2723040, public'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'application/octet-stream'
 - Content-Length: '119999'
 - Content-Range: 'bytes 0-119998/119999'
 - Accept-Ranges: 'bytes'
----------------------
Segmentation fault (core dumped)
```

**Comment by mgautierfr** [comment]
It seems that the `A/Minneapolis_Saint_Paul.html` leads to a article redirecting to itself (so infinite loop).

This a "problem" in the zim file itself but it is something we cannot really change.
The crash was because of a bug in kiwix-serve and I've fixed it (now return a 404).

It could be interesting to have the sources used to create the zim file to check if it is a bug in zimwriterfs or in mwoffliner. But 2009 is a pretty old zim, you probably not have them.

**Comment by kelson42** [comment]
@mgautierfr I feel quite stupid, I do not understand your one line fix! How moving from max 43 redirections to 42 should avoid a crash? For the rest, Nothing in the format really avoids that kind of loop, so the ZIM is valid... but IMO a check to detect this should be integrated in "zimcheck" (see https://github.com/openzim/zim-tools/issues/6)

**Comment by mgautierfr** [comment]
Because of the test `if (loopCounter == 42)` after the loop.

If we post-increment `while ( … && loopCounter++ < 42)` at last loop, `loopCounter` (==42) will be compared to 42 and then incremented (so will be equal to 43). So the `if` will not work and the article will be invalid.

If we pre-increment, in the last loop, `loopCounter` (==41) will be incremented (==42) and then compared to 42).

**Comment by kelson42** [comment]
@mgautierfr got it, the problem is a bit later https://github.com/kiwix/kiwix-tools/blob/8b6abc0e35be8177901f7972e7eb6fecffcad366/src/server/kiwix-serve.cpp#L634

Thx
