### ISSUE TITLE
Strange inconsistencies with suggestions

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#175]
Both should give the same result, but they do not.

```
$ ./kiwix-search -s wikipedia_fr_all_novid_2018-03.zim "antoine marc"
Antoine Marcas
Antoine Marcourt
Antoine Marcotte
Marc Antoine Muret
Marc-Antoine Taxil
Marc-Antoine Nadon
Marc-Antoine Jamet
Marc-Antoine Soucy
Marc-Antoine Sartre
Marc-Antoine Commaire
kelson@camber:/tmp/kiwix-tools_linux64-2018-04-09$ ./kiwix-search -s wikipedia_fr_all_novid_2018-03.zim "marc antoine"
Marc Antoine
Marc Antoine Muret
Marc-Antoine Taxil
Marc Antoine Baudot
Marc-Antoine Nadon
Marc-Antoine Jamet
Marc-Antoine Puvis
Marc Antoine Gaudin
Marc-Antoine Soucy
Marc-Antoine Petit
```

I slowly doubt the Levenstein approach is a good one.

**Comment by kelson42** [comment]
With latest version of kiwix-serve/zim. The problem is still there:
```
$ kiwix-search -s wikipedia_fr_all_mini_2019-08.zim "antoine marc"
$ kiwix-search -s wikipedia_fr_all_mini_2019-08.zim "marc antoine"
Marc Antoine
Antoine Marc
Marc-Antoine
Marc-Antoine (homonymie)
Marc-Antoine Fortuné
Marc Antoine Lacuée
Marc-Antoine Dominicy
Marc-Antoine Quantin
Marc-Antoine Charrier
Marc-Antoine Hersan
```

**Comment by mgautierfr** [comment]
Here the comment of the commit fixing this :

---
This is a bit tricky.

We used to, at indexing, to stem the term using the STEM_ALL strategy.
This strategy stems all words and keep only the stemmed term as is.
At searching, we were doing the same when parsing the query.


But now, for title indexing (suggestion), we use the STEM_SOME strategy.
This strategy stems some words but also keep the unstemmed term.
The stem term is keep with the `Z` prefix.
If, at searching, we use the STEM_ALL strategy. We will search for
the stemmed term without `Z` prefix and so, we will never find it.
Using the STEM_SOME add the `Z` prefix to

As an example :

"marc antoine" is indexed using the STEM_SOME strategy some we have the
terms `marc`, `antoine` and `Zantoin`

If we search for "marc antoine" with STEM_ALL, we will search for
"marc AND (WILDCARD SYNONYM antoine OR antoin" and we will have results
(because marc and antoine are present)

But if we search for "antoine marc", we will search for
"antoin AND (WILDCARD SYNONYM marc OR marc)". As there is no term "antoin"
there will be no result.

If stem with STEM_SOME, the query will be
"Zantoin AND (WILDCARD SYNONYM marc OR Zmarc)". And we have results.

---

I copy it because it is interesting and leads to some a more general question of "How we should index the content ?".
