### ISSUE TITLE
Why was kiwix-tools release from 2018-06-20 overwritten on 2018-08-24?

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#222]
@mgautierfr why did all the kiwix-tools 0.6.0 tar.gz's (from 2018-06-20) disappear from http://download.kiwix.org/release/kiwix-tools/ on 2018-08-24, each overwritten with much smaller tar.gz's ?

_Did you mean to release 0.6.1 or 0.7.0, and accidentally overwrite the older release?_

Aside: I'm impressed with the new weight-loss program (e.g. kiwix-tools_linux-x86_64-0.6.0.tar.gz is now 59% smaller than it was a week ago, if indeed this is intentional) and am happy that a new release is happening...is there a changelog or similar possible?

PS I have copies of the original 0.6.0 here if it helps: http://download.iiab.io/packages/

**Comment by mgautierfr** [comment]
`kiwix-tools` depends on other dependencies as `kiwix-lib` or `libzim`.
When we do a new release of this dependencies, we also rebuild `kiwix-tools` even if there is no new release of `kiwix-tools`.

> Did you mean to release 0.6.1 or 0.7.0, and accidentally overwrite the older release?

There is no `0.6.1` nor `0.7.0` This is still version `0.6.0`(but build with different dependencies)

> is there a changelog or similar possible?

Each repository has a Changelog file.
The release build are made on `kiwix-build` repository. The version used are set in https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/versions.py
The release build is triggered by a tag on `kiwix-build`. At now, the last tag is `0.0.8` (dated from `2018-08-24`). Tag from 2018-06-20 is `0.0.6`. Comparing the `version.py` file from `0.0.6` and `0.0.8`, we can see that we moved `libzim` from` 4.0.0` to `4.0.3` and `kiwix-lib` from `2.0.1` to `2.0.2`

> I'm impressed with the new weight-loss program (e.g. kiwix-tools_linux-x86_64-0.6.0.tar.gz is now 59% smaller than it was a week ago, if indeed this is intentional) 

This was not intentional, but I'm happy about this :)
From 0.0.6 to 0.0.8 we also change xapian (from `1.4.5` to `1.4.7`) and we now deactivate the `chert` backend. It may explain the weight-loss.

**Comment by kelson42** [comment]
@mgautierfr things in release/ should IMO never be overwritten.

**Comment by holta** [comment]
Thanks @mgautierfr for the careful explanation.

With such a major restructuring of the internals, can we consider naming this 0.6.1 to avoid confusion across the community?

**Comment by mgautierfr** [comment]
> With such a major restructuring of the internals, can we consider naming this 0.6.1 to avoid confusion across the community?

No but yes.
- **No**, There is strictly no change in `kiwix-tools` between the two builds. We use the exact same sources. What was the version of the dependencies `kiwix-tools` was build on is not the problem of the `kiwix-tools` project. So I will no rename a build of `0.6.0` to `0.6.1`. And it will add more confusion when we will actually release `0.6.1`.
- **Yes**, but there are some minor changes made on `kiwix-tools` on top of `0.6.0`. We can actually release a new `0.6.1` version.

**Comment by holta** [comment]
Fantastic news.

Will `0.6.1` appear at http://download.kiwix.org/release/kiwix-tools/ within 24h or so?

> Each repository has a Changelog file.
The release build are made on kiwix-build repository. The version used are set in https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/versions.py

Thanks!  I've now found the equivalent URL for kiwix-tools:

https://github.com/kiwix/kiwix-tools/blob/master/Changelog

**Comment by mgautierfr** [comment]
> Will 0.6.1 appear at http://download.kiwix.org/release/kiwix-tools/ within 24h or so?

Yes, 0.6.1 is already tagged. It is just about the time to have kiwix-build being updated and build the binaries.
