### ISSUE TITLE
Consider not compiling jQuery into kiwix-serve?

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-tools#249]
After a bit of debugging, I realized that kiwix-serve contains all of the jQuery JS and CSS in the binary itself.

This is somewhat problematic from a Debian packaging perspective, mostly because if we want to change the JS code, it requires recompiling kiwix-serve.

A little background, Debian would prefer it (though it's not a hard requirement) if packages used the packaged version of jQuery and jQuery UI, just like any other library dependency. But if we have to recompile kiwix-serve every time, that's pretty problematic.

Could kiwix-serve look for the JS resources in `/usr/share/kiwix-serve/jquery/` or similar? That way those can be updated without requiring recomplication.

If there's a specific reason that the bundled jquery/jquery-ui need to be used, I can figure out a different approach that way as well.

**Comment by kelson42** [comment]
@legoktm We do that way to propose binaries which "just work", but I understand what you say. @mgautierfr would that be able to have compilation option allowing to deal with external version of jquery?

**Comment by mgautierfr** [comment]
JQuery is only used for its autocomplete function to provide input completion on the searchbar.
I think we could use a different system (a quick search point me to https://github.com/Pixabay/JavaScript-autoComplete) instead of integrating a full jQuery library (outdated by the way)

I'm a bit afraid to be dependent of a files installed outwhere in the system. It would lead to the kiwix-tools package being dependent of jQuery package (and the kiwx-tools project not being dependent of jQuery).
What happen if the files are not present or cannot be read for some reason ?

**Comment by kelson42** [comment]
To me changing the library is just a workaround. I would stick to JQuery. It is quite clear anyway that this page (and the searchbar) will be rewritten anyway soon. Regarding the dependency to jquery, it is like any other dependence, it has to be there and the packaging system should secure this. That said, I would prefer that we do not touch this for now, IMO this is quite a bit of work, it is not the best moment and it seems not to be 100% mandatory. @legoktm Could you live with the current situation for now?

**Comment by int19h** [comment]
Is this blocking the Kiwix package in Buster? I notice that libkiwix-dev and all other dependencies are already packaged, but kiwix-tools is still in limbo.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856595

**Comment by kelson42** [comment]
@legoktm Could you please confirm if this is a blocker or not?

**Comment by legoktm** [comment]
This is no longer an issue.
