### ISSUE TITLE
kiwix-serve: Too many redirects

### ISSUE THREAD

**Issue by joe218376de** [kiwix/kiwix-tools#292]
when I enter in the search field "ju 52"
or when I enter direct the url
http://localhost:8787/wikipedia_de_all_novid_2018-11/A/Junkers_Ju_52_3m.html

I get

Fehler: Umleitungsfehler "Die aufgerufene Website leitet die Anfrage so um, dass sie nie beendet werden kann."

translated
Error: Redirect Error "Die called website redirects requests in a never ending loop."

The following url works but is another article (1m instead of 3m)
http://localhost:8787/wikipedia_de_all_novid_2018-11/A/Junkers_Ju_52_1m.html

kiwix-serve of kiwixtools 1.2.1 has the bug with

wikipedia_de_all_novid_2018-11 - in new zim format
wikipedia_de_all_novid_2018-06 - in new zim format
and also in
wikipedia_de_all_novid_2017-08 - in OLD zim format

The bug does not occur in the current android kiwix app and also not
in the current kiwix mozilla plugin 2.5.0, and also not in kiwix-serve of kiwix-0.9,
which understood only the old zim format.

**Comment by kelson42** [comment]
@joe218376de Thank you for taking the time to report that problem. There is no problem in kiwix-serve I think, it does its job. I can not explain exactly why Kiwix for Android would work. But what happens here is that we have online "Junkers_Ju_52_3m" redirecting to "Junkers_Ju_52/3m"... and in the ZIM files both are represented with the same URL "Junkers_Ju_52_3m.html" in the A namespace. So depending a bit about how things are implemented, this creates a selft redirecting redirect. With mwoffliner 1.8, the scraper with use since May, the "/" will kep in the URL in the future ZIM file and then the problem will be fixed. You just need to be a bit patient to get the new version of the ZIM file.

**Comment by joe218376de** [comment]
@kelson42, thanks for investigating the issue, and finding an explanation.

when you have 2 items for the same url in the zim, you should prefer the one which is no redirect ... no idea whether this is possible so quick.

**Comment by kelson42** [comment]
@joe218376de In fact we should not allow to write duplicates URLs in the ZIM file. This is one root of the pb https://github.com/openzim/libzim/issues/213

**Comment by joe218376de** [comment]
Perfect! Many thanks to you and Matthieu.
