### ISSUE TITLE
kiwix-serve exits if declared index present

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#30]
version: http://download.kiwix.org/nightly/2017-04-30/kiwix-tools_armhf_2017-04-30.tar.gz (download and untar)

download and unzip http://download.kiwix.org/portable/wikipedia/kiwix-0.9+wikipedia_en_for-schools_2013-01.zip

put all .zim* files into /library/zims/content and zim.idx directory into /library/zims/index

/opt/schoolserver/kiwix/bin/kiwix-manage /library/zims/library.xml add /library/zims/content/wikipedia_en_for_schools_opt_2013.zim -i /library/zims/index/wikipedia_en_for_schools_opt_2013.zim.idx (N.B. index exists)

run /opt/schoolserver/kiwix/bin/kiwix-serve --port 3000 --library /library/zims/library.xml
navigate browser to host:3000 and load Wikipedia for Schools

enter 'children' in search field

-rw-r--r-- 1 root root 133637738 Apr 30 14:44 kiwix-tools_armhf_2017-04-30.tar.gz
root@box:/opt/schoolserver/kiwix/bin# /opt/schoolserver/kiwix/bin/kiwix-serve --port 3000 --library /library/zims/library.xml
terminate called after throwing an instance of 'Xapian::InvalidArgumentError'
Aborted

previously kiwix-serve showed a list of articles with the word 'children' (I take it as self-evident that this is the preferred behavior)

**Comment by tim-moody** [comment]
This is my top issue as of May 13, 2017.

**Comment by holta** [comment]
Emmanuel & Matthieu,

Thanks so much for your incredible, ongoing work here looking into this tough issue!

I'm speaking to several countries/communities Monday and this coming week who are very eager (OK, desperate is the unvarnished truth ;-) for some kind of resolution here, even if it's just a prelim diagnosis/prognosis possibly in coming days?

(So that their legacy ZIM's [with external indexes] hopefully continue to work despite the [famous Chrome browser bug](https://github.com/kiwix/kiwix-tools/issues/15), as all eagerly anticipating migrating to this new kiwix-serve very soon we hope, as well as [increasingly] new ZIM's with internal indexes over the coming months!)

Adam (holt @ laptop.org)

PS excited to see you Matthieu & all soon in Montreal August ~9th, and during the 4.5 days after Wikimania 2017 @ our http://OFF.NETWORK hackathon, that I and Martin Walker are facilitating, hoping you can make time for both...14 months after we all met in Italy!

**Comment by tim-moody** [comment]
superseded by #35
