### ISSUE TITLE
docker "Unable to add the ZIM file 'wikipedia_zh_all_maxi_2019-10.zim' to the internal library."

### ISSUE THREAD

**Issue by woshichuanqilz** [kiwix/kiwix-tools#362]
I use docker on  Windows 10

follow the steps here https://hub.docker.com/r/kiwix/kiwix-serve. 

My zim file is in E drive I share the e drive and get the shared path `//Sc-201912272219/e` the name of the zim file is `wikipedia_zh_all_maxi_2019-10.zim`

my command is `docker run -v //Sc-201912272219/e:/data -p 8080:80 kiwix/kiwix-serve wikipedia_zh_all_maxi_2019-10.zim`

But get this error:
> /usr/local/bin/kiwix-serve --port=80 wikipedia_zh_all_maxi_2019-10.zim
Unable to add the ZIM file 'wikipedia_zh_all_maxi_2019-10.zim' to the internal library.

how to fix this?

**Comment by kelson42** [comment]
@woshichuanqilz I'm not familliar with Windows and Docker on Windows. But the command looks OK, and kiwix-serve is started.

Therefore, the only reason why it fails is that the `wikipedia_zh_all_maxi_2019-10.zim` is not there, probably because the mount point does do what you think.

I just have added a small debug message which show the content of `/data` if `kiwix-serve` can not start properly. If you pull again `kiwix/kiwix-serve` image you will see it and this will help you to understand the problem I believe.

**Comment by kelson42** [comment]
@woshichuanqilz Have you been able to diagnose the problem with most recent version of the container?

**Comment by kelson42** [comment]
No feedback, I close the ticket.

**Comment by monstermaker** [comment]
Having this issue with the stackoverflow.com_en_all_nopic_2022_07.zim file. the debug message says;
Here is the content of /data:
/data/stackoverflow.com_en_all_nopic_2022_07.zim

I have checked the permissions on the file and set it to 777 temporarily to make sure that permissions are not the issue. I am not sure if the leading /data is correct and the content of /data should be stackoverflow.com_en_all_nopic_2022_07.zim and not /data/stackoverflow.com_en_all_nopic_2022_07.zim

**Comment by kelson42** [comment]
@monstermaker please open a new ticket with all the details about what you run, the system and the error/terminal output.
