### ISSUE TITLE
Publish an ARM based Docker image (on hub.docker.com)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#410]
More and more people use kiwix-serve on ARM based GNU/Linux and more and more people uses Docker on ARM based GNU/Linux. This is why I believe, this might be helpful. Seems doable and relatively easy by following this example:
https://hub.docker.com/r/ckulka/multi-arch-example

**Comment by maneeshpm** [comment]
Hey @kelson42 ! If this issue is still open, I would like to work on it.
After going through [this](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/), I understand there are two ways of doing it, one of which is experimental using Docker buildx. As the example you shared mentions, pushing images to Docker hub and referencing them in the manifest file seems to be the better solution.

**Comment by Ayushsunny** [comment]
I wanna work on this issue.

**Comment by rgaudin** [comment]
@Ayushsunny I am already assigned on this issue. This is being worked on and should land-in today. As @kelson42 mentioned, we are trying to standardize the way we build and publish our images and this is part of this effort.

**Comment by kelson42** [comment]
Done https://hub.docker.com/r/kiwix/kiwix-serve/tags?page=1&ordering=last_updated
