### ISSUE TITLE
Kiwix-serve should be able to mimick/spoof download.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#411]
People connected to the Kiwix-hotspot (which uses Kiwix-serve) and launching the Kiwix app should be able to read the catalogue of zim files available on the hotspot (and download them).

**Comment by mgautierfr** [comment]
There is two part here :
- Have the user application ask the catalog the the kiwix-hotspot instead of library.kiwix.org.
  This need some configuration on the application (kiwix-desktop/anddroid/...)  (we don't have)
  It would be better to have some "auto configuration" but I don't know how to do it right now.
  In all case, the final configuration (auto or not) would be on the kiwix-hotspot administrator.
- Downloading the file from the hotspot. https://github.com/kiwix/kiwix-tools/issues/344 already exist for this point. As I said there, I think it should be to the hotspot administrator to configure a static server for the zim content and configure kiwix-serve to point to this url (as it is made in library.kiwix.org)

**Comment by kelson42** [comment]
Closing basically a duplicate of https://github.com/kiwix/kiwix-hotspot/issues/540. I believe the idea was similar to https://github.com/kiwix/kiwix-tools/issues/344, which might not be a good idea at all.
