### ISSUE TITLE
Support for load multiple zim and merge/override them

### ISSUE THREAD

**Issue by zkosk** [kiwix/kiwix-tools#441]
Now Wiki max zim update each 2 months which needs 480GB/year SSD write (use the zim from HDD has much slower search speed).

Topics like history/art/math does't need frequent update. Each user need different topics to be up to date.

Using one old Wiki max zim and up to date zims for sub topics works but is not easy.

Can the kiwix-serve support loading multiple zim and override one with the other? Such as:

kiwix-serve.exe wiki-maxi-old.zim -overrride topic1.zim -override topic2.zim

This may also need a update of the offlining tools or even the format.

**Comment by kelson42** [comment]
It is impossible to partiatly (only a few articles) update ZIM files easily, because these articles have links which point to other articles (which are maybe new and which should be mirrored as well). Your approach would create large amount of broken links.... and this is only one of many problem this approach would create.

The solution is having a better multzim mgmt, this would allow to search only in part of the articles, set priority in result search, etc...
