### ISSUE TITLE
Kiwix-serve welcome page not optimised

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#538]
See:

![5ABEFE45-9CD4-4FDE-AD01-D19B64ED4A81](https://user-images.githubusercontent.com/1029718/153743002-48e1f36a-d9a6-43a6-83f6-93532dab6150.png)

The problem here is that we should be able to see 3 tiles in a row, not inly 2.

I believe the problem comes from the default margin left, which applies as well to the filters: this is too high. Or at least, it shoukd be able to be smaller.

**Comment by ankur12-1610** [comment]
@kelson42 I would like to work on this issue!

**Comment by ankur12-1610** [comment]
@kelson42 I'm unable to reproduce this issue. In my case it has 3 rows.
![kiwix-tools](https://user-images.githubusercontent.com/76884959/154256799-fc95434d-e1bf-4cb2-9ed2-e43df832474e.png)

**Comment by ankur12-1610** [comment]
> See:
> 
> ![5ABEFE45-9CD4-4FDE-AD01-D19B64ED4A81](https://user-images.githubusercontent.com/1029718/153743002-48e1f36a-d9a6-43a6-83f6-93532dab6150.png)
> 
> The problem here is that we should be able to see 3 tiles in a row, not inly 2.
> 
> I believe the problem comes from the default margin left, which applies as well to the filters: this is too high. Or at least, it shoukd be able to be smaller.

@kelson42 I could you specify at which particular media query did this happen? Cause it has the same layout as you want in my local host.

**Comment by kelson42** [comment]
@ankur12-1610 Imade this screenshot with an ipad, give a try to the responsive mode of your browser.

**Comment by ankur12-1610** [comment]
> @ankur12-1610 Imade this screenshot with an ipad, give a try to the responsive mode of your browser.

Ah! got it, @kelson42 I understood the issue and I know how to solve but the problem now is where are the CSS files, how `kiwix-tools` uses CSS, does it uses skin from another kiwix project or :sweat_smile:

**Comment by kelson42** [comment]
All in libkiwix

**Comment by ankur12-1610** [comment]
> All in libkiwix

I've raised a PR, kindly review.
Thanks!

**Comment by juuz0** [comment]
Can I take this?
Related to https://github.com/kiwix/libkiwix/issues/585

**Comment by eroyee** [comment]
Sorry to jump on this late, but I've just had time to try 3.3.0, previously I was using a nightly build from June '21.

I believe this is related, but if you'd prefer me to raise a separate issue please say so; I feel the screen realestate that's taken up by the whitespace in the new 'square' tiles is also pertinent here. With the attached example above the whitespace between "From Wikiversity" to "EN" etc probably doubles the required vertical space for the tile.

In the earlier version there was little additional whitespace with the rectangular tiles, which I think made quite a difference with the number of tiles you could show - particularly with a small screen (although one could display three across, so I can't compare exactly).

If it were possible to either remove the whitespace, or pass an option for the earlier layout, maybe that could assist those wishing to display many zim files in a single window? I realise there's a category filter option that can reduce the number of tiles displayed, but this does involve the user more, and in some cases could be unnecessary.

Otherwise thanks for the new stackoverflow.com_en_all_2022-05.zip which addresses https://github.com/kiwix/kiwix-tools/issues/463 👍
