### ISSUE TITLE
kiwix-serve: update manpage

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-tools#609]
Most parameters listed in [the usage help text](https://github.com/kiwix/kiwix-tools/blob/main/src/server/kiwix-serve.cpp#L45) of `kiwix-serve` are missing from the manpage.

**Comment by kelson42** [comment]
Agree!

**Comment by PK284** [comment]
@kelson42 Kindly assign me on this would like to update the Man Page.

**Comment by premkirank** [comment]
I would like to work on this issue. Can you assign this to me.

**Comment by premkirank** [comment]
@kelson42 can't I build this on macOS?

**Comment by kelson42** [comment]
@premkirank If you have a real problem to build, then please open an other ticket.

**Comment by iArchitSharma** [comment]
Can you please assign this to me I have already started working on it

**Comment by iArchitSharma** [comment]
Missing Parameter:
-h, --help: Print a help message and exit.
-a, --attachToProcess: Exit if given process id is not running anymore.
-i, --address: Listen only on this IP address, all available ones otherwise.
-M, --monitorLibrary: Monitor the XML library file and reload it automatically.
-c, --customIndex: Add path to custom index.html for the welcome page.
-n, --nosearchbar: Don't print the builtin bar overlay on the top of each served page.
-b, --blockexternal: Prevent users from directly accessing external links.
-r, --urlRootLocation: URL prefix on which the content should be made available (default: /).
-t, --threads: Number of threads to run in parallel (default: 4).
-L, --ipConnectionLimit: Maximum number of (concurrent) connections per IP (default: infinite, recommended: >= 6).
-s, --searchLimit: Maximum number of ZIM in a full-text multizim search (default: no limit).

**Comment by iArchitSharma** [comment]
#626 Made the PR
