### ISSUE TITLE
 [Regression]Search and Auto Suggestion Broken for Chinese in 3.7.0 Release

### ISSUE THREAD

**Issue by lovenemesis** [kiwix/kiwix-tools#671]
This is a follow-up report against 3.7.0 release of the original reported #657 since that was Closed.

Using 3.7.0 kiwix-manage arm64 build on a Raspberry Pi, the issue persists, even with the latest "wikivoyage_zh_all_maxi_2024-03" release.

```
kiwix-tools 3.7.0

libkiwix 13.1.0
+ libzim 9.1.0
+ libxapian 1.4.23
+ libcurl 7.67.0
+ libmicrohttpd 0.9.76
+ libz 1.2.12
+ libicu 73.2.0
+ libpugixml 0.12.0

libzim 9.1.0
+ libzstd 1.5.2
+ liblzma 5.2.6
+ libxapian 1.4.23
+ libicu 73.2.0
```

3.7.0 behaves very much like 3.6.0.
I had to revert to 3.5.0 to get proper search behaviors.

Let me know if anything else I need to provide to diagnose the issue.

**Comment by mgautierfr** [comment]
As said in #657, this is a a problem in the zim file itself, not in the reader software.
This has been fixed in creator with this PR : https://github.com/openzim/libzim/pull/806

The current issue is on mwoffliner which still use a old version of the libzim (https://github.com/openzim/mwoffliner/issues/1576)
MwOffliner is used to create all mediawiki sites so all `wiki*` zim files are impacted.
