### ISSUE TITLE
kiwix-serve LIBRARY_PATH does not resolve relative paths

### ISSUE THREAD

**Issue by jonboiser** [kiwix/kiwix-tools#70]
Found this bug at the SUNY Potsdam hackthon.

Environment is a Docker container running Ubuntu Xenial with the 8/13/17 Nightly build of kiwix-tools. [Here](https://github.com/jonboiser/dockerized-kiwix-server) is the github project for the Docker.

Assume that `library.xml` is at `/`

```
root@75aabacd457d:/# pwd
/

root@75aabacd457d:/# kiwix-serve --library ./library.xml
Unable to open the XML library file './library.xml'.

root@75aabacd457d:/# kiwix-serve --library /library.xml
(server is running)
```

**Comment by kelson42** [comment]
@mgautierfr any chance to have this bug fixed for next nightly build, so @jonboiser might benefit of this during the hackathon?

**Comment by ranguli** [comment]
This issue is still occuring on Arch using kiwix from the AUR, but providing tthe absolute path of a library file fixed it. Can't seem to get Kiwix to report a version number to let you know what it is either. If it was fixed I'm assuming the AUR package is just out of date.  Just a heads up to any Arch users who are still experiencing this.

**Comment by kelson42** [comment]
@ranguli This sounds like an AUR packaging problem!?

The AUR packaging is old and maintained. The packager had a hard time as everything (kiwix-desktop and kiwix-serve) were distributed together by us in the past. This is not the case anymore. kiwix-serve is part of the command-line only toolset "kiwix-tools". kiwix-tools is now released "properly" and the tarball can be found here https://download.kiwix.org/release/kiwix-tools/. We hope this will help AUR packager in his work.
