### ISSUE TITLE
search results have zim:// url

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#72]
I never noticed this before. 

using 8/28 build with url http://iiab.me:3000/wikipedia_en_medicine_2017-02/
search for cardiac and select 'containing cardiac'

all search results begin with zim:// which for me does not exist

internal page links look like http://iiab.me:3000/wikipedia_en_medicine_2017-02/A/Pulmonary_embolism.html as before

**Comment by kelson42** [comment]
@mgautierfr I did not monitor in detail enought this stuff about "prefix"... but of course nothing in kiwix-lib neither in zimlib should be added at protocol. I suspect here this is exactly what has been done.

**Comment by tim-moody** [comment]
I now can not reproduce with nightly from 8/28 and am wondering if this was cached from a previous version. Can you verify the problem with the links above?

**Comment by mgautierfr** [comment]
It was a bug in kiwix-serve and global search.
We were (internally) not properly configuring the html template engine for the search result and use the default protocol (`zim://`)
This has been fixed in "recent" version of kiwix-serve (https://github.com/kiwix/kiwix-tools/commit/7776eafbfc45ab9b81102159af2ed868cd2e56dc).

This is probably a cached search result from a previous version of kiwix-serve with the bug.
I'm closing the issue. Reopen it if I'm wrong.
